-- MySQL Script generated by MySQL Workbench
-- Mon May 13 09:55:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Product
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Product
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Product` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema assignment
-- -----------------------------------------------------
USE `Product` ;

-- -----------------------------------------------------
-- Table `Product`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product`.`Product` ;

CREATE TABLE IF NOT EXISTS `Product`.`Product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `long_description` TEXT NOT NULL,
  `short_description` VARCHAR(255) NOT NULL,
  `availability` TINYINT NOT NULL,
  `country_of_origin` VARCHAR(45) NOT NULL,
  `weight` DECIMAL NOT NULL,
  `price` FLOAT NOT NULL,
  `delivery_cost` FLOAT NOT NULL,
  `roast` VARCHAR(45) NOT NULL,
  `grind` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product`.`Customer` ;

CREATE TABLE IF NOT EXISTS `Product`.`Customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `customer_image` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `is_admin` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(6) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `email` VARCHAR(125) NOT NULL,
  `tastes` VARCHAR(45) NOT NULL,
  `method_of_payment` VARCHAR(45) NULL,
  `order_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product`.`Orders` ;

CREATE TABLE IF NOT EXISTS `Product`.`Orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `price` FLOAT NOT NULL,
  `cost` FLOAT NOT NULL,
  `quantity` INT NOT NULL,
  `delivery_cost` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Product`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`.`Order/Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product`.`Order/Product` ;

CREATE TABLE IF NOT EXISTS `Product`.`Order/Product` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `cost` FLOAT NOT NULL,
  `quantity` DECIMAL NOT NULL,
  `subtotal` FLOAT NOT NULL,
  `taxes` FLOAT NOT NULL,
  `delivery_cost` FLOAT NOT NULL,
  `total` DECIMAL NOT NULL,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `Product`.`Orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
